/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.chicha.ttt.extractor.timeago.patterns;

import org.chicha.ttt.extractor.timeago.PatternsHolder;

public class en extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"second", "seconds"},
            MINUTES  /**/ = {"minute", "minutes"},
            HOURS    /**/ = {"hour", "hours"},
            DAYS     /**/ = {"day", "days"},
            WEEKS    /**/ = {"week", "weeks"},
            MONTHS   /**/ = {"month", "months"},
            YEARS    /**/ = {"year", "years"};

    private static final en INSTANCE = new en();

    public static en getInstance() {
        return INSTANCE;
    }

    private en() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}