/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package org.chicha.ttt.extractor.timeago.patterns;

import org.chicha.ttt.extractor.timeago.PatternsHolder;

public class si extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"තත්පර"},
            MINUTES  /**/ = {"මිනිත්තු"},
            HOURS    /**/ = {"පැය"},
            DAYS     /**/ = {"දින"},
            WEEKS    /**/ = {"සති"},
            MONTHS   /**/ = {"මාස"},
            YEARS    /**/ = {"වසර"};

    private static final si INSTANCE = new si();

    public static si getInstance() {
        return INSTANCE;
    }

    private si() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}